#!/bin/bash -e
#SBATCH --job-name=rduplex_aso
#SBATCH --account=ACCOUNT  # replace with your HPC project account
#SBATCH --time=00:10:00
#SBATCH --mem=1G
#SBATCH --cpus-per-task=1
#SBATCH --output=logs/rduplex_aso.%j.out
#SBATCH --error=logs/rduplex_aso.%j.err

# Run RNAduplex for allele-selectivity scoring on HPC.
# Covers both common SNP handles and pathogenic SNVs.
#
# Workflow:
#   1. Local:  generate duplex inputs (step 1 of add_extended_aso_scores.sh)
#              e.g. run the script up to step 1 or extract the Python block
#   2. HPC:    sbatch run_rduplex_aso.sl
#   3. Local:  SKIP_RDUPLEX=1 ./add_extended_aso_scores.sh
#
# Prereqs (generated by step 1 of add_extended_aso_scores.sh):
#   results/rduplex/{common_snps,pathogenic_missense}.aso_ref.match.in
#   results/rduplex/{common_snps,pathogenic_missense}.aso_ref.mismatch.in
#   results/rduplex/{common_snps,pathogenic_missense}.aso_alt.match.in
#   results/rduplex/{common_snps,pathogenic_missense}.aso_alt.mismatch.in

module purge
module load ViennaRNA/2.4.17-gimkl-2020a

mkdir -p results/rduplex logs

echo "RNAduplex: $(which RNAduplex)"
RNAduplex --version || true
echo

for CLASS in common_snps pathogenic_missense; do
  for ARM in aso_ref.match aso_ref.mismatch aso_alt.match aso_alt.mismatch; do
    echo "  ${CLASS}.${ARM} ..."
    RNAduplex < results/rduplex/${CLASS}.${ARM}.in \
      > results/rduplex/${CLASS}.${ARM}.out
  done
  echo "  ${CLASS}: done"
done

echo "Done."
