#!/bin/bash
#SBATCH --job-name=aso_offtarget
#SBATCH --account=YOUR_ACCOUNT
#SBATCH --time=01:00:00
#SBATCH --mem=16G
#SBATCH --cpus-per-task=8
#SBATCH --output=logs/offtarget_%j.out
#SBATCH --error=logs/offtarget_%j.err

# Off-target search: bowtie2, end-to-end mode, up to 2 mismatches (no indels).
# Run after 01_make_aso_queries.py and 02_build_indices.sh.
# After this: run 05_annotate_repeats.sh, then 04_parse_offtargets.py --repeats ...
#
# Submit: sbatch scripts/03_search_offtargets.sl
# Locally: bash scripts/03_search_offtargets.sl

set -euo pipefail
mkdir -p logs results/offtarget

# ---- modules (adjust for your HPC scheduler or comment out to use system tools) ----
module load Bowtie2 2>/dev/null || true

IDXD="data/bowtie_indices"
OUTD="results/offtarget"
THREADS="${SLURM_CPUS_PER_TASK:-4}"

# Query FASTAs generated by 01_make_aso_queries.py
QUERIES=(
  "${OUTD}/queries_common_ref.fa"
  "${OUTD}/queries_common_alt.fa"
  "${OUTD}/queries_pathogenic_alt.fa"
  "${OUTD}/queries_pathogenic_ref.fa"
)

# Indices to search against
declare -A INDICES=(
  ["transcriptome"]="${IDXD}/transcriptome"
  ["premrna"]="${IDXD}/premrna"
)
# Optionally add genome:
# INDICES["genome"]="${IDXD}/genome"

run_bowtie() {
    local index="$1"
    local index_name="$2"
    local query="$3"
    local query_name=$(basename "${query}" .fa)
    local out="${OUTD}/${query_name}_vs_${index_name}.bwt"

    if [ -f "${out}" ]; then
        echo "Skipping (exists): ${out}"
        return
    fi

    echo "Searching ${query_name} vs ${index_name} ..."
    bowtie2 \
        -p "${THREADS}" \
        --end-to-end \
        --no-unal \
        --norc \
        --score-min L,-12,0 \
        --mp 6,6 \
        --rdg 100,100 \
        --rfg 100,100 \
        -k 200 \
        -f \
        -x "${index}" \
        -U "${query}" \
        -S "${out}"

    echo "Done: ${out}"
}

for query in "${QUERIES[@]}"; do
    [ -f "${query}" ] || { echo "Missing: ${query}"; continue; }
    for index_name in "${!INDICES[@]}"; do
        run_bowtie "${INDICES[$index_name]}" "${index_name}" "${query}"
    done
done

echo "All bowtie searches complete."
